

module.exports = {
    database : {
	address : 'localhost:27017/siak_proto'
    },
    gamedatadir : './game_data/',
    audioconf : {
	'fs'                     : 16000,
	'max_utterance_length_s' : 10,
	'max_packet_length_s'    : 1,
	'packets_per_second'     : 3,
	'datatype_length'        : 4,
	'frame_step_samples'     : 128,
	'frame_length_samples'   : 400,
	'frame_step_bits'        : 512,
	'frame_length_bits'      : 16000,
	'feature_dim'            : 30,
	'pitch_low'              : 60,
	'pitch_high'             : 240,
	'lsforder'               : 15,
	'lsflength'              : 16, // Should be order +1
	'mceporder'              : 12,
	'mceplength'             : 13,
	'mcepindexes'            : [0,1,2,3,4,5,6,7,8,9,10,11,12],
	'f0indexes'              : [13],
	'lsfindexes'             : [14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],
	'dimensions'             : 30, // 16 + 13 + 1
	'debug_mfcc'             : true,
	'debug_f0'               : true,
	'debug_lsf'              : true
    },
    recogconf : {
	'grammar' : 'words.conf',
	'packet_size' : 2048,
	'pause_between_packets' : 20,
	'lexicon' : '/home/backend/models-clean-am/train.lex',
	//'model' : '/home/backend/models/siak_clean_b/siak_clean_b'
	'model_source' : '/home/backend/models/siak_clean_a',
	'model_cache' : '/dev/shm/siak_models/',
	'model' : '/dev/shm/siak_models/siak_clean_a/siak_clean_a',
	'flag_use_adaptation': 0,
	//'model' : '/home/backend/models/mc-am_2016-06-11/siak_mc_a',
	'word_modeldir' : '/l/data/siak-server-devel/models/clean-am/'
    },
    dnnconf : {
	'port' : 16054,
	'datadim' : 30,
	'timesteps' : 63,
	'datasize' : 4,
	'port_number_file' : '/home/backend/siak-server/keras_server/ports/portnr'
	//'model_arch_file':  '/l/data/siak-server-devel/server/dnn_models/l1000_d0.6-2016-07-12-architecture.json',
	//'model_weight_file' : '/l/data/siak-server-devel/server/dnn_models/l1000_d0.6-2016-07-12-weights.26-1.54.hdf5',
	//'model_norm_file' : '/l/data/siak-server-devel/server/dnn_models/clean.mean_and_std.pkl'

    },
    temp_devel_stuff : {
	'good_utterance_length_s' : 3
    },
    vad : {
	'window' : 160*4, // VAD window size (10ms of 16kHz 4bit float data)
	'speech_frame_thr' : 5, // How many consecutive speech frames are needed for a speech segment decision
	'sil_frame_thr' : 20, // How many consecutive silence frames are needed for a silence segment decision,
	'extra_end_sil' : 12800, // 200ms => 3200 samples => 3200 * 4 bits 
	'extra_start_sil' : 12800 // 200ms => 3200 samples => 3200 * 4 bits 
    },
    word_lists: 
    {
	L0: {
	    apple: {en: "apple", fi: "omena", count: 0 },
	    baseball: {en: "baseball", fi: "baseball", count: 0 },
	    age: {en: "age", fi: "ikä", count: 0 },
	    pig: {en: "pig", fi: "sika", count: 0 },
	    please: {en: "please", fi: "ole hyvä, kiitos", count: 0 },
	    elephant: {en: "elephant", fi: "norsu", count: 0 },
	    choose: {en: "choose", fi: "valita", count: 0 },
	    too : {en: 'too', fi: "myös", count: 0 },
	    monkey : {en: 'monkey', fi: "apina", count: 0},
	    look : {en: 'look', fi: "katsoa", count: 0},
	    long: {en: 'long', fi: "pitkä", count: 0}
	},

	L1: {
	    hello : { en: "hello", fi: "hei", count: 0 },
	    bye_bye : { en: "bye bye", fi: "hei hei", count: 0 },
	    school : { en: "school", fi: "koulu", count: 0 },
	    home : { en: "home", fi: "koti", count: 0 },
	    friend : { en: "friend", fi: "ystävä", count: 0 },
	    boy : { en: "boy", fi: "poika", count: 0 },
	    girl : { en: "girl", fi: "tyttö", count: 0 },
	    speak : { en: "speak", fi: "puhua", count: 0 },
	    play  : { en: "play ", fi: "pelata/leikkiä", count: 0 },
	    book : { en: "book", fi: "kirja", count: 0 },
	    say : { en: "say", fi: "sanoa", count: 0 },
	    come_on : { en: "come on", fi: "tule", count: 0 },
	    sorry : { en: "sorry", fi: "anteeksi", count: 0 },
	    read : { en: "read", fi: "lukea", count: 0 },
	    write : { en: "write", fi: "kirjoittaa", count: 0 }
	},


	L2: {
	    air : { en: "air", fi: "ilma", count: 0 },
	    bush : { en: "bush", fi: "pensas", count: 0 },
	    forest : { en: "forest", fi: "metsä", count: 0 },
	    tree : { en: "tree", fi: "puu", count: 0 },
	    flower : { en: "flower", fi: "kukka", count: 0 },
	    lake : { en: "lake", fi: "järvi", count: 0 },
	    leaf : { en: "leaf", fi: "lehti", count: 0 },
	    life : { en: "life", fi: "elämä", count: 0 },
	    light : { en: "light", fi: "valo", count: 0 },
	    moon : { en: "moon", fi: "kuu", count: 0 },
	    plant : { en: "plant", fi: "kasvi", count: 0 },
	    rock : { en: "rock", fi: "kivi", count: 0 },
	    sand : { en: "sand", fi: "hiekka", count: 0 },
	    sea : { en: "sea", fi: "meri", count: 0 },
	    river : { en: "river", fi: "joki", count: 0 },
	    sun : {en: "sun", fi: "aurinko", count : 0 }
	},

	L3: {
	    quiet : { en: "quiet", fi: "hiljainen", count: 0 },
	    round : { en: "round", fi: "pyöreä", count: 0 },
	    wrong : { en: "wrong", fi: "väärä", count: 0 },
	    right  : { en: "right ", fi: "oikea", count: 0 },
	    dark : { en: "dark", fi: "pimeä", count: 0 },
	    dry : { en: "dry", fi: "kuiva", count: 0 },
	    low : { en: "low", fi: "matala", count: 0 },
	    soft : { en: "soft", fi: "pehmeä", count: 0 },
	    wet : { en: "wet", fi: "märkä", count: 0 },
	    bad : { en: "bad", fi: "huono", count: 0 },
	    good : { en: "good", fi: "hyvä", count: 0 },
	    loud : { en: "loud", fi: "äänekäs", count: 0 },
	    high : { en: "high", fi: "korkea", count: 0 },
	    cool : { en: "cool", fi: "viileä, hieno", count: 0 },
	    hard : { en: "hard", fi: "kova", count: 0 }
	},


	L4: {
	    farmer : { en: "farmer", fi: "maanviljelijä", count: 0 },
	    pig : { en: "pig", fi: "sika", count: 0 },
	    sheep : { en: "sheep", fi: "lammas", count: 0 },
	    mouse : { en: "mouse", fi: "hiiri", count: 0 },
	    horse : { en: "horse", fi: "hevonen", count: 0 },
	    cat : { en: "cat", fi: "kissa", count: 0 },
	    cow : { en: "cow", fi: "lehmä", count: 0 },
	    dog : { en: "dog", fi: "koira", count: 0 },
	    hen : { en: "hen", fi: "kana", count: 0 },
	    chicken : { en: "chicken", fi: "tipu, kana", count: 0 },
	    country : { en: "country", fi: "maaseutu", count: 0 },
	    field : { en: "field", fi: "pelto", count: 0 },
	    grass : { en: "grass", fi: "ruoho/nurmi", count: 0 },
	    hay : { en: "hay", fi: "heinä", count: 0 },
	    duck : { en: "duck", fi: "ankka/sorsa", count: 0 }
	},


	L5: {
	    food : { en: "food", fi: "ruoka", count: 0 },
	    apple : { en: "apple", fi: "omena", count: 0 },
	    bake : { en: "bake", fi: "leipoa", count: 0 },
	    berry : { en: "berry", fi: "marja", count: 0 },
	    breakfast : { en: "breakfast", fi: "aamupala", count: 0 },
	    bread : { en: "bread", fi: "leipä", count: 0 },
	    butter : { en: "butter", fi: "voi", count: 0 },
	    cake : { en: "cake", fi: "kakku", count: 0 },
	    candy : { en: "candy", fi: "karkki", count: 0 },
	    carrot : { en: "carrot", fi: "porkkana", count: 0 },
	    cook : { en: "cook", fi: "laittaa ruokaa", count: 0 },
	    cut : { en: "cut", fi: "leikata", count: 0 },
	    drink : { en: "drink", fi: "juoda", count: 0 },
	    eat : { en: "#eat", fi: "syödä", count: 0 },
	    lunch : { en: "lunch", fi: "lounas" , count: 0 }
	},

	L6: {
	    shirt : { en: "shirt", fi: "paita", count: 0 },
	    Shoe : { en: "Shoe", fi: "kenkä", count: 0 },
	    Socks : { en: "Socks", fi: "sukat", count: 0 },
	    cap : { en: "cap", fi: "lippalakki", count: 0 },
	    coat : { en: "coat", fi: "takki", count: 0 },
	    hat : { en: "hat", fi: "hattu", count: 0 },
	    buy : { en: "buy", fi: "ostaa", count: 0 },
	    wash  : { en: "wash ", fi: "pestä", count: 0 },
	    money : { en: "money", fi: "raha", count: 0 },
	    belt : { en: "belt", fi: "vyö", count: 0 },
	    Wear : { en: "Wear", fi: "käyttää", count: 0 },
	    fit : { en: "fit", fi: "mahtua/sopia", count: 0 },
	    shop : { en: "shop", fi: "kauppa", count: 0 },
	    best  : { en: "best ", fi: "paras", count: 0 },    
	},


	L7: {
	    ball : { en: "ball", fi: "pallo", count: 0 },
	    baseball : { en: "baseball", fi: "pesäpallo", count: 0 },
	    basketball : { en: "basketball", fi: "koripallo", count: 0 },
	    fun : { en: "fun", fi: "huvi/hauska", count: 0 },
	    game : { en: "game", fi: "peli", count: 0 },
	    goal : { en: "goal", fi: "maali", count: 0 },
	    ice_hockey : { en: "ice hockey", fi: "jääkiekko", count: 0 },
	    ice_skating : { en: "ice skating", fi: "luistelu", count: 0 },
	    movie : { en: "movie", fi: "elokuva", count: 0 },
	    music : { en: "music", fi: "musiikki", count: 0 },
	    sing : { en: "sing", fi: "laulaa", count: 0 },
	    ski : { en: "ski", fi: "hiihtää", count: 0 },
	    swim : { en: "swim", fi: "uida", count: 0 },
	    win : { en: "win", fi: "voittaa", count: 0 },
	    party : { en: "party", fi: "juhlat", count: 0 },
	},


	L8: {
	    pet : { en: "pet", fi: "lemmikki", count: 0 },
	    neighbour : { en: "neighbour", fi: "naapuri", count: 0 },
	    classmate : { en: "classmate", fi: "luokkatoveri/luokkakaveri", count: 0 },
	    sister : { en: "sister", fi: "sisko", count: 0 },
	    teacher : { en: "teacher", fi: "opettaja", count: 0 },
	    child : { en: "child", fi: "lapsi", count: 0 },
	    children : { en: "children", fi: "lapset", count: 0 },
	    family : { en: "family", fi: "perhe", count: 0 },
	    man : { en: "man", fi: "mies", count: 0 },
	    woman : { en: "woman", fi: "nainen", count: 0 },
	    parents : { en: "parents", fi: "vanhemmat", count: 0 },
	    love : { en: "love", fi: "rakastaa", count: 0 },
	    baby : { en: "baby", fi: "vauva", count: 0 },
	    young : { en: "young", fi: "nuori", count: 0 },
	    old	: { en: "old", fi: "vanha", count: 0 }
	},

	L9: {
	    dessert : { en: "dessert", fi: "jälkiruoka", count: 0 },
	    fork : { en: "fork", fi: "haarukka", count: 0 },
	    glass : { en: "glass", fi: "lasi", count: 0 },
	    knife : { en: "knife", fi: "veitsi", count: 0 },
	    lick : { en: "lick", fi: "nuolaista/nuolla", count: 0 },
	    make : { en: "make", fi: "tehdä/valmistaa", count: 0 },
	    more : { en: "more", fi: "lisää/enemmän", count: 0 },
	    plate : { en: "plate", fi: "lautanen", count: 0 },
	    spoon : { en: "spoon", fi: "lusikka", count: 0 },
	    sweet : { en: "sweet", fi: "makea", count: 0 },
	    pepper : { en: "pepper", fi: "pippuri", count: 0 },
	    pear : { en: "pear", fi: "päärynä", count: 0 },
	    meat : { en: "meat", fi: "liha", count: 0 },
	    cup : { en: "cup", fi: "kuppi", count: 0 },
	    water : { en: "water", fi: "vesi", count: 0 },
	    milk: { en: "milk", fi: "maito", count: 0 }
	},

	L10: {
	    cheek : { en: "cheek", fi: "poski", count: 0 },
	    chin : { en: "chin", fi: "leuka", count: 0 },
	    ear : { en: "ear", fi: "korva", count: 0 },
	    eye : { en: "eye", fi: "silmä", count: 0 },
	    face : { en: "face", fi: "kasvot", count: 0 },
	    nose : { en: "nose", fi: "nenä", count: 0 },
	    lips : { en: "lips", fi: "huulet", count: 0 },
	    tongue : { en: "tongue", fi: "kieli", count: 0 },
	    hear : { en: "hear", fi: "kuulla", count: 0 },
	    feel : { en: "feel", fi: "tuntea", count: 0 },
	    taste : { en: "taste", fi: "maistaa/maku", count: 0 },
	    smell  : { en: "smell ", fi: "haistaa/haju", count: 0 },
	    sound : { en: "sound", fi: "ääni", count: 0 },
	    look : { en: "look", fi: "katsoa/katso", count: 0 },
	    listen : { en: "listen", fi: "kuunnella/kuuntele", count: 0 }
	},

	L11: {
	    arm : { en: "arm", fi: "käsivarsi", count: 0 },
	    back : { en: "back", fi: "selkä", count: 0 },
	    elbow : { en: "elbow", fi: "kyynärpää", count: 0 },
	    feet : { en: "feet", fi: "jalat/jalkaterät", count: 0 },
	    finger : { en: "finger", fi: "sormi", count: 0 },
	    hair : { en: "hair", fi: "hiukset", count: 0 },
	    hand : { en: "hand", fi: "käsi", count: 0 },
	    neck : { en: "neck", fi: "kaula", count: 0 },
	    body  : { en: "body ", fi: "vartalo", count: 0 },
	    legs : { en: "legs", fi: "jalat/sääret", count: 0 },
	    shoulder : { en: "shoulder", fi: "olkapää", count: 0 },
	    knee : { en: "knee", fi: "polvi", count: 0 },
	    toe : { en: "toe", fi: "varvas", count: 0 },
	    run  : { en: "run ", fi: "juosta", count: 0 },
	    jump  : { en: "jump ", fi: "hypätä", count: 0 },
	},


	L12: {
	    cheese : { en: "cheese", fi: "juusto", count: 0 },
	    cherry : { en: "cherry", fi: "kirsikka", count: 0 },
	    chew : { en: "chew", fi: "pureskella", count: 0 },
	    chip : { en: "chip", fi: "hippu", count: 0 },
	    chocolate : { en: "chocolate", fi: "suklaa", count: 0 },
	    cucumber : { en: "cucumber", fi: "kurkku", count: 0 },
	    lemon : { en: "lemon", fi: "sitruuna", count: 0 },
	    meatball : { en: "meatball", fi: "lihapulla", count: 0 },
	    potato : { en: "potato", fi: "peruna", count: 0 },
	    salad : { en: "salad", fi: "salaatti", count: 0 },
	    salt : { en: "salt", fi: "suola", count: 0 },
	    snack : { en: "snack", fi: "välipala", count: 0 },
	    soup : { en: "soup", fi: "keitto", count: 0 },
	    toast : { en: "toast", fi: "paahtoleipä", count: 0 },
	    tomato : { en: "tomato", fi: "tomaatti", count: 0 },
	    strawberry : { en: "strawberry", fi: "mansikka", count: 0 },
	    jam : { en: "jam", fi: "hillo", count: 0 },
	    juice : { en: "juice", fi: "mehu", count: 0 },
	},


	L13: {
	    I : { en: "I", fi: "minä", count: 0 },
	    you : { en: "you", fi: "sinä", count: 0 },
	    he : { en: "he", fi: "hän, sanotaan pojasta tai miehestä", count: 0 },
	    she : { en: "she", fi: "hän, sanotaan tytöstä tai naisesta", count: 0 },
	    we : { en: "we", fi: "me", count: 0 },
	    you  : { en: "you ", fi: "te", count: 0 },
	    it : { en: "#it", fi: "se", count: 0 },
	    don_t : { en: "don't", fi: "älä", count: 0 },
	    come : { en: "come", fi: "tulla", count: 0 },
	    go : { en: "go", fi: "mennä", count: 0 },
	    want : { en: "want", fi: "haluta", count: 0 },
	    like : { en: "like", fi: "tykätä", count: 0 },
	    give : { en: "give", fi: "antaa", count: 0 },
	    take : { en: "take", fi: "ottaa", count: 0 },
	    learn : { en: "learn", fi: "oppia", count: 0 },
	},

	L14: {
	    i_am : { en: "I am", fi: "minä olen", count: 0 },
	    you_are : { en: "you are", fi: "sinä olet", count: 0 },
	    she_is : { en: "she is", fi: "hän on", count: 0 },
	    i_was : { en: "I was", fi: "minä olin", count: 0 },
	    you_were : { en: "you were", fi: "sinä olit", count: 0 },
	    we_were : { en: "we were", fi: "me olimme/me oltiin", count: 0 },
	    i_go : { en: "I go", fi: "minä menen", count: 0 },
	    you_go  : { en: "you go ", fi: "sinä menet", count: 0 },
	    he_goes : { en: "he goes", fi: "hän menee", count: 0 },
	    we_go : { en: "we go", fi: "me menemme/me mennään", count: 0 },
	    let_s_go  : { en: "Let's go ", fi: "mennään", count: 0 },
	    i_like : { en: "I like", fi: "minä tykkään", count: 0 },
	    she_likes : { en: "she likes", fi: "hän tykkää", count: 0 },
	    hurry_up : { en: "hurry up", fi: "kiirehdi/vauhtia!", count: 0 },
	},


	L15: {
	    one : { en: "one", fi: "yksi", count: 0 },
	    two : { en: "two", fi: "kaksi", count: 0 },
	    four : { en: "four", fi: "neljä", count: 0 },
	    five : { en: "five", fi: "viisi", count: 0 },
	    six : { en: "six", fi: "kuusi", count: 0 },
	    seven : { en: "seven", fi: "seitsemän", count: 0 },
	    eight : { en: "eight", fi: "kahdeksan", count: 0 },
	    nine : { en: "nine", fi: "yhdeksän", count: 0 },
	    ten : { en: "ten", fi: "kymmenen", count: 0 },
	    Hundred : { en: "Hundred", fi: "sata", count: 0 },
	    four_cars : { en: "four cars", fi: "neljä autoa", count: 0 },
	    five_cups : { en: "five cups", fi: "viisi kuppia", count: 0 },
	    two_cats : { en: "two cats", fi: "kaksi kissaa", count: 0 },
	    eight_balls : { en: "eight balls", fi: "kahdeksan palloa", count: 0 }
	},


	L16: {
	    bear : { en: "bear", fi: "karhu", count: 0 },
	    bee : { en: "bee", fi: "mehiläinen", count: 0 },
	    bird : { en: "bird", fi: "lintu", count: 0 },
	    bug : { en: "bug", fi: "ötökkä", count: 0 },
	    butterfly : { en: "butterfly", fi: "perhonen", count: 0 },
	    dolphin : { en: "dolphin", fi: "delfiini", count: 0 },
	    hare : { en: "hare", fi: "jänis", count: 0 },
	    elephant : { en: "elephant", fi: "norsu", count: 0 },
	    fish : { en: "fish", fi: "kala", count: 0 },
	    fox : { en: "fox", fi: "kettu", count: 0 },
	    hedgehog : { en: "hedgehog", fi: "siili", count: 0 },
	    lion : { en: "lion", fi: "leijona", count: 0 },
	    monkey : { en: "monkey", fi: "apina", count: 0 },
	    owl : { en: "owl", fi: "pöllö", count: 0 },
	    snake : {en: "snake", fi: "käärme", count: 0 }
	},

	L17: {
	    ice  : { en: "ice ", fi: "jää", count: 0 },
	    eyes : { en: "eyes", fi: "silmät", count: 0 },
	    once : { en: "once", fi: "kerran", count: 0 },
	    ones : { en: "ones", fi: "yhdet", count: 0 },
	    peace : { en: "peace", fi: "rauha", count: 0 },
	    peas : { en: "peas", fi: "herneet", count: 0 },
	    place : { en: "place", fi: "paikka", count: 0 },
	    plays : { en: "plays", fi: "leikkii/pelaa", count: 0 },
	    rice : { en: "rice", fi: "riisi", count: 0 },
	    rise : { en: "rise", fi: "nousta", count: 0 },
	    sauce : { en: "sauce", fi: "kastike", count: 0 },
	    saws : { en: "saws", fi: "sahat", count: 0 },
	    Zoo : { en: "Zoo", fi: "eläintarha", count: 0 },
	    zoos : { en: "zoos", fi: "eläintarhat", count: 0 },
	    see : { en: "see", fi: "nähdä", count: 0 },
	    sees : {en: "sees", fi: "näkee", count: 0 }
	},

	L18: {
	    thick : { en: "thick", fi: "paksu", count: 0 },
	    thin : { en: "thin", fi: "ohut", count: 0 },
	    thing : { en: "thing", fi: "juttu", count: 0 },
	    think : { en: "think", fi: "ajatella", count: 0 },
	    teeth : { en: "teeth", fi: "hammas, hampaat", count: 0 },
	    mouth : { en: "#mouth", fi: "suu", count: 0 },
	    north : { en: "north", fi: "pohjoinen", count: 0 },
	    theatre : { en: "theatre", fi: "teatteri", count: 0 },
	    month : { en: "month", fi: "kuukausi", count: 0 },
	    three : { en: "three", fi: "kolme", count: 0 },
	    thank_you : { en: "thank you", fi: "kiitos", count: 0 },
	    thirsty : { en: "thirsty", fi: "janoinen", count: 0 },
	    throw : { en: "throw", fi: "heittää", count: 0 },
	    bath : { en: "bath", fi: "kylpy", count: 0 },
	    maths : { en: "maths", fi: "matematiikka", count: 0 }  
	},


	L19: {
	    brother : { en: "brother", fi: "veli", count: 0 },
	    father : { en: "father", fi: "isä", count: 0 },
	    mother  : { en: "mother ", fi: "äiti", count: 0 },
	    clothes : { en: "#clothes", fi: "vaatteet", count: 0 },
	    their : { en: "their", fi: "heidän", count: 0 },
	    they : { en: "they", fi: "he", count: 0 },
	    then : { en: "then", fi: "sitten", count: 0 },
	    there : { en: "there", fi: "tuolla", count: 0 },
	    this : { en: "this", fi: "tämä", count: 0 },
	    that : { en: "that", fi: "tuo, että", count: 0 },
	    theese : { en: "theese", fi: "nämä", count: 0 },
	    those : { en: "those", fi: "nuo", count: 0 },
	    than : { en: "than", fi: "kuin", count: 0 },
	    the : {en: "the", fi: "(määräinen artikkeli)", count: 0},
	    with : { en: "with", fi: "kanssa", count: 0 },
	},


	L20: {
	    bedroom : { en: "bedroom", fi: "makuuhuone", count: 0 },
	    carpet : { en: "carpet", fi: "matto", count: 0 },
	    bed : { en: "bed", fi: "sänky", count: 0 },
	    sleep : { en: "sleep", fi: "nukkua", count: 0 },
	    dream : { en: "dream", fi: "uneksia/uni", count: 0 },
	    garage : { en: "garage", fi: "autotalli", count: 0 },
	    house : { en: "house", fi: "talo", count: 0 },
	    kitchen : { en: "kitchen", fi: "keittiö", count: 0 },
	    lamp : { en: "lamp", fi: "lamppu", count: 0 },
	    living_room : { en: "living room", fi: "olohuone", count: 0 },
	    lock : { en: "lock", fi: "lukita/lukko", count: 0 },
	    phone : { en: "phone", fi: "puhelin", count: 0 },
	    room : { en: "room", fi: "huone", count: 0 },
	    shower : { en: "shower", fi: "suihku", count: 0 },
	    table : { en: "table", fi: "pöytä", count: 0 },
	    toilet : { en: "toilet", fi: "vessa", count: 0 },
	    window : { en: "window", fi: "ikkuna", count: 0 },
	    door : {en: "door", fi: "ovi", count: 0 }
	},

	L21: {
	    black : { en: "black", fi: "musta", count: 0 },
	    blue : { en: "blue", fi: "sininen", count: 0 },
	    brown : { en: "brown", fi: "ruskea", count: 0 },
	    green : { en: "green", fi: "vihreä", count: 0 },
	    grey : { en: "grey", fi: "harmaa", count: 0 },
	    orange : { en: "orange", fi: "oranssi", count: 0 },
	    pink : { en: "pink", fi: "vaaleanpunainen", count: 0 },
	    purple : { en: "purple", fi: "violetti", count: 0 },
	    red : { en: "red", fi: "punainen", count: 0 },
	    white : { en: "white", fi: "valkoinen", count: 0 },
	    yellow : { en: "yellow", fi: "keltainen", count: 0 },
	    colour : { en: "colour", fi: "väri", count: 0 },
	    paint : { en: "paint", fi: "maali", count: 0 },
	    art : { en: "art", fi: "taide", count: 0 },
	    draw : {en: "draw", fi: "piirtää", count: 0 }
	},


	L22: {
	    ice  : { en: "ice ", fi: "jää", count: 0 },
	    eyes : { en: "eyes", fi: "silmät", count: 0 },
	    once : { en: "once", fi: "kerran", count: 0 },
	    ones : { en: "ones", fi: "yhdet", count: 0 },
	    peace : { en: "peace", fi: "rauha", count: 0 },
	    peas : { en: "peas", fi: "herneet", count: 0 },
	    place : { en: "place", fi: "paikka", count: 0 },
	    plays : { en: "plays", fi: "leikkii/pelaa", count: 0 },
	    rice : { en: "rice", fi: "riisi", count: 0 },
	    rise : { en: "rise", fi: "nousta", count: 0 },
	    sauce : { en: "sauce", fi: "kastike", count: 0 },
	    saws : { en: "saws", fi: "sahat", count: 0 },
	    Zoo : { en: "Zoo", fi: "eläintarha", count: 0 },
	    zoos : { en: "zoos", fi: "eläintarhat", count: 0 },
	    see : { en: "see", fi: "nähdä", count: 0 },
	    sees : {en: "sees", fi: "näkee", count: 0 }
	},

	L23: {
	    thick : { en: "thick", fi: "paksu", count: 0 },
	    thin : { en: "thin", fi: "ohut", count: 0 },
	    thing : { en: "thing", fi: "juttu", count: 0 },
	    think : { en: "think", fi: "ajatella", count: 0 },
	    teeth : { en: "teeth", fi: "hammas, hampaat", count: 0 },
	    mouth : { en: "#mouth", fi: "suu", count: 0 },
	    north : { en: "north", fi: "pohjoinen", count: 0 },
	    theatre : { en: "theatre", fi: "teatteri", count: 0 },
	    month : { en: "month", fi: "kuukausi", count: 0 },
	    three : { en: "three", fi: "kolme", count: 0 },
	    thank_you : { en: "thank you", fi: "kiitos", count: 0 },
	    thirsty : { en: "thirsty", fi: "janoinen", count: 0 },
	    throw : { en: "throw", fi: "heittää", count: 0 },
	    bath : { en: "bath", fi: "kylpy", count: 0 },
	    maths : { en: "maths", fi: "matematiikka", count: 0 }  
	},


	L24: {
	    brother : { en: "brother", fi: "veli", count: 0 },
	    father : { en: "father", fi: "isä", count: 0 },
	    mother  : { en: "mother ", fi: "äiti", count: 0 },
	    clothes : { en: "#clothes", fi: "vaatteet", count: 0 },
	    their : { en: "their", fi: "heidän", count: 0 },
	    they : { en: "they", fi: "he", count: 0 },
	    then : { en: "then", fi: "sitten", count: 0 },
	    there : { en: "there", fi: "tuolla", count: 0 },
	    this : { en: "this", fi: "tämä", count: 0 },
	    that : { en: "that", fi: "tuo, että", count: 0 },
	    theese : { en: "theese", fi: "nämä", count: 0 },
	    those : { en: "those", fi: "nuo", count: 0 },
	    than : { en: "than", fi: "kuin", count: 0 },
	    the : {en: "the", fi: "(määräinen artikkeli)", count: 0},
	    with : { en: "with", fi: "kanssa", count: 0 },
	},


	L25: {
	    here : { en: "here", fi: "täällä/tässä", count: 0 },
	    where : { en: "where", fi: "missä", count: 0 },
	    who : { en: "who", fi: "kuka", count: 0 },
	    what : { en: "what", fi: "mikä/mitä", count: 0 },
	    why : { en: "why", fi: "miksi", count: 0 },
	    now : { en: "now", fi: "nyt", count: 0 },
	    today : { en: "today", fi: "tänään", count: 0 },
	    yesterday : { en: "yesterday", fi: "eilen", count: 0 },
	    tomorrow : { en: "tomorrow", fi: "huomenna", count: 0 },
	    time : { en: "time", fi: "aika", count: 0 },
	    day : { en: "day", fi: "päivä", count: 0 },
	    evening	 : { en: "evening	", fi: "ilta", count: 0 },
	    morning : { en: "morning", fi: "aamu", count: 0 },
	    night : { en: "night	", fi: "yö", count: 0 },
	    week : { en: "week	", fi: "viikko", count: 0 },
	    year : { en: "year	", fi: "vuosi", count: 0 },
	},


	L26: {
	    language : { en: "language", fi: "kieli", count: 0 },
	    english : { en: "English", fi: "englannin kieli", count: 0 },
	    finnish : {en: "Finnish", fi: "suomen kieli", count: 0 },
	    swedish : { en: "Swedish", fi: "ruotsin kieli", count: 0 },
	    finland : { en: "Finland", fi: "Suomi ", count: 0 },
	    finn : { en: "Finn", fi: "suomalainen, sanotaan ihmisestä", count: 0 },
	    england : { en: "England", fi: "Englanti", count: 0 },
	    europe : { en: "Europe", fi: "Eurooppa", count: 0 },
	    live : { en: "live", fi: "elää", count: 0 },
	    city : { en: "city", fi: "kaupunki/suurkaupunki", count: 0 },
	    town : { en: "town", fi: "kaupunki/pikkukaupunki", count: 0 },
	    village : { en: "village", fi: "kylä", count: 0 },
	    age : { en: "age", fi: "ikä", count: 0 },
	    
	},


	L27: {
	    ice  : { en: "ice ", fi: "jää", count: 0 },
	    eyes : { en: "eyes", fi: "silmät", count: 0 },
	    once : { en: "once", fi: "kerran", count: 0 },
	    ones : { en: "ones", fi: "yhdet", count: 0 },
	    peace : { en: "peace", fi: "rauha", count: 0 },
	    peas : { en: "peas", fi: "herneet", count: 0 },
	    place : { en: "place", fi: "paikka", count: 0 },
	    plays : { en: "plays", fi: "leikkii/pelaa", count: 0 },
	    rice : { en: "rice", fi: "riisi", count: 0 },
	    rise : { en: "rise", fi: "nousta", count: 0 },
	    sauce : { en: "sauce", fi: "kastike", count: 0 },
	    saws : { en: "saws", fi: "sahat", count: 0 },
	    Zoo : { en: "Zoo", fi: "eläintarha", count: 0 },
	    zoos : { en: "zoos", fi: "eläintarhat", count: 0 },
	    see : { en: "see", fi: "nähdä", count: 0 },
	    sees : {en: "sees", fi: "näkee", count: 0 }
	},

	L28: {
	    thick : { en: "thick", fi: "paksu", count: 0 },
	    thin : { en: "thin", fi: "ohut", count: 0 },
	    thing : { en: "thing", fi: "juttu", count: 0 },
	    think : { en: "think", fi: "ajatella", count: 0 },
	    teeth : { en: "teeth", fi: "hammas, hampaat", count: 0 },
	    mouth : { en: "#mouth", fi: "suu", count: 0 },
	    north : { en: "north", fi: "pohjoinen", count: 0 },
	    theatre : { en: "theatre", fi: "teatteri", count: 0 },
	    month : { en: "month", fi: "kuukausi", count: 0 },
	    three : { en: "three", fi: "kolme", count: 0 },
	    thank_you : { en: "thank you", fi: "kiitos", count: 0 },
	    thirsty : { en: "thirsty", fi: "janoinen", count: 0 },
	    throw : { en: "throw", fi: "heittää", count: 0 },
	    bath : { en: "bath", fi: "kylpy", count: 0 },
	    maths : { en: "maths", fi: "matematiikka", count: 0 }  
	},


	L29: {
	    brother : { en: "brother", fi: "veli", count: 0 },
	    father : { en: "father", fi: "isä", count: 0 },
	    mother  : { en: "mother ", fi: "äiti", count: 0 },
	    clothes : { en: "#clothes", fi: "vaatteet", count: 0 },
	    their : { en: "their", fi: "heidän", count: 0 },
	    they : { en: "they", fi: "he", count: 0 },
	    then : { en: "then", fi: "sitten", count: 0 },
	    there : { en: "there", fi: "tuolla", count: 0 },
	    this : { en: "this", fi: "tämä", count: 0 },
	    that : { en: "that", fi: "tuo, että", count: 0 },
	    theese : { en: "theese", fi: "nämä", count: 0 },
	    those : { en: "those", fi: "nuo", count: 0 },
	    than : { en: "than", fi: "kuin", count: 0 },
	    the : {en: "the", fi: "(määräinen artikkeli)", count: 0},
	    with : { en: "with", fi: "kanssa", count: 0 },
	},


	L30: {
	    would_you_like_some_juice : { en: "Would you like some juice?", fi: "Haluaisitko mehua?", count: 0 },
	    would_you_like_some_more : { en: "Would you like some more?", fi: "Haluaisitko lisää?", count: 0 },
	    yes_please	 : { en: "Yes, please	", fi: "Kyllä, kiitos.", count: 0 },
	    no_thank_you : { en: "No, thank you", fi: "Ei kiitos", count: 0 },
	    you_re_welcome : { en: "Youre welcome", fi: "Ole hyvä (kun on kiitetty)", count: 0 },
	    here_you_are : { en: "Here you are", fi: "Ole hyvä (kun annetaan jotakin)", count: 0 },
	    well_done : { en: "Well done", fi: "Hyvin tehty", count: 0 },
	    my_name_is  : { en: "My name is ", fi: "minun nimeni on", count: 0 },
	    nice_to_meet_you : { en: "Nice to meet you", fi: "Mukava tutustua.", count: 0 },
	    i_live_in_finland	 : { en: "I live in Finland	", fi: "Asun Suomessa", count: 0 },
	    i_speak_finnish	 : { en: "I speak Finnish	", fi: "Puhun suomea", count: 0 },
	    i_am_sorry  : { en: "I am sorry ", fi: "Anteeksi/olen pahoillani", count: 0 },
	    come_here : { en: "come here", fi: "tule tänne", count: 0 },
	    good_evening : { en: "good evening", fi: "hyvää iltaa", count: 0 },
	    good_morning : { en: "good morning", fi: "huomenta", count: 0 },
	    good_night : { en: "good night", fi: "hyvää yötä", count: 0 },
	    do_you_want_to_play_with_us : { en: "Do you want to play with us?", fi: "Haluatko leikkiä kanssamme?", count: 0 }
	}
    }
}
